<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.mpower.test.ReportSourceTest" failures="3" tests="4" time="148.673" errors="0">
  <properties/>
  <testcase name="createReportSources" time="142.908" classname="com.mpower.test.ReportSourceTest">
    <failure type="java.lang.IllegalArgumentException" message="Unknown entity: com.mpower.domain.ReportDataSource">
      <![CDATA[java.lang.IllegalArgumentException: Unknown entity: com.mpower.domain.ReportDataSource
	at org.hibernate.ejb.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:215)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:194)
	at $Proxy13.persist(Unknown Source)
	at com.mpower.dao.JPAReportDataSourceDao.save(JPAReportDataSourceDao.java:23)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:310)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:89)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at $Proxy14.save(Unknown Source)
	at com.mpower.service.ReportSourceImpl.save(ReportSourceImpl.java:25)
	at com.mpower.test.ReportSourceTest.createReportSources(ReportSourceTest.java:34)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:140)
... Removed 36 stack frames]]>
    </failure>
  </testcase>
  <testcase name="findReportSource" time="0.015" classname="com.mpower.test.ReportSourceTest">
    <failure type="java.lang.IllegalArgumentException" message="Unknown entity: com.mpower.domain.ReportDataSource">
      <![CDATA[java.lang.IllegalArgumentException: Unknown entity: com.mpower.domain.ReportDataSource
	at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:185)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:194)
	at $Proxy13.find(Unknown Source)
	at com.mpower.dao.JPAReportDataSourceDao.findById(JPAReportDataSourceDao.java:34)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:310)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:89)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at $Proxy14.findById(Unknown Source)
	at com.mpower.service.ReportSourceImpl.find(ReportSourceImpl.java:30)
	at com.mpower.test.ReportSourceTest.findReportSource(ReportSourceTest.java:47)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:140)
Caused by: org.hibernate.MappingException: Unknown entity: com.mpower.domain.ReportDataSource
	at org.hibernate.impl.SessionFactoryImpl.getEntityPersister(SessionFactoryImpl.java:550)
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:68)
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:878)
	at org.hibernate.impl.SessionImpl.get(SessionImpl.java:815)
	at org.hibernate.impl.SessionImpl.get(SessionImpl.java:808)
	at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:174)
	... 51 more
... Removed 36 stack frames]]>
    </failure>
  </testcase>
  <testcase name="listReportSource" time="3.954" classname="com.mpower.test.ReportSourceTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.mpower.test.ReportSourceTest.listReportSource(ReportSourceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:140)
... Removed 28 stack frames]]>
    </failure>
  </testcase>
  <testcase name="emptyTest" time="0.0040" classname="com.mpower.test.ReportSourceTest"/>
</testsuite>
